---
- name: Write custom server configuration
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0644
  #notify:
  #  - stop percona
  #  - clear iblogfiles
  #  - start percona
  register: mysql_config_status
  tags: [ mysql ]

- name: Remove default logs
  file: path={{ item }} state=absent
  with_items:
    - /var/log/mysql.log
    - /var/log/mysql.err
  tags: [ mysql ]

- name: Stop server for delete binary logs
  service: name=mysql state=stopped
  when: mysql_installation|changed or mysql_config_status|changed
  tags: [ mysql, delete_binary_logs ]

- name: Delete binary logs
  file: path={{ item }} state=absent
  with_items:
    - "{{ mysql_datadir }}/ib_logfile0"
    - "{{ mysql_datadir }}/ib_logfile1"
  when: mysql_installation|changed or mysql_config_status|changed
  tags: [ mysql, delete_binary_logs ]

- name: Start server after delete binary logs
  service: name=mysql state=started
  when: mysql_installation|changed or mysql_config_status|changed
  tags: [ mysql, delete_binary_logs ]

- name: Check mysql running
  service: name=mysql state=started
  tags: [ mysql ]

- name: Update MySQL root password
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    check_implicit_admin=yes
  with_items:
    - "{{ ansible_nodename }}"
    - 127.0.0.1
    - localhost
    #- '::1' # fails on first password update
  tags: [ mysql ]

- name: Copy .my.cnf file into the root home folder
  template: src=root-my-cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: [ mysql ]

# must run after .my.cnf update
- name: Update MySQL root password for ::1
  mysql_user:
    name=root
    host='::1'
    password={{ mysql_root_password }}
    check_implicit_admin=yes
  tags: [ mysql ]

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - "{{ ansible_nodename }}"
    - localhost
  tags: [ mysql ]

- name: remove test database
  mysql_db: name=test state=absent
  tags: [ mysql ]
