---

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Check percona datadir
  stat:
    path: /var/lib/percona-server
  register: mysql_register_percona_datadir
  
- name: Install percona database server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - percona-server-server-5.6
    #- percona-server-client-5.6
    - percona-toolkit
    - percona-xtrabackup
    - python-mysqldb
  register: mysql_installation

- name: Delete default percona-server datadir
  file: 
    path: /var/lib/percona-server
    state: absent
  when: mysql_datadir != '/var/lib/percona-server' and mysql_register_percona_datadir.stat.exists == false
