---

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: [ mysql ]

- name: Install percona database server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - percona-server-server-5.6
    #- percona-server-client-5.6
    - percona-toolkit
    - percona-xtrabackup
    - python-mysqldb
  register: mysql_installation
  tags: [ mysql ]
