---

# repo

- name: Obtaining percona public key
  apt_key:
    url=http://www.percona.com/downloads/RPM-GPG-KEY-percona
    state=present
  tags: [ mysql ]

- name: Adding percona repository
  apt_repository:
    repo="deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    state=present
  tags: [ mysql ]

- name: Adding percona source repository
  apt_repository:
    repo="deb-src http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    state=present
  tags: [ mysql ]

- name: Update apt cache
  apt:
    update_cache=yes
    cache_valid_time=3600
  tags: [ mysql ]


# install

- name: Ensure MySQL server is uninstalled
  action: apt pkg={{ item }} state=absent
  with_items:
    - mysql-server-core-5.5
    - mysql-client
    - mysql-client-5.5
    - mysql-client-core-5.5
  tags: [ mysql ]

- name: Install percona database server
  action: apt pkg={{ item }} state=latest
  with_items:
    - percona-server-server-5.5
    - percona-server-client-5.5
    - percona-toolkit
    - percona-xtrabackup
    - python-mysqldb
  register: mysql_installation
  tags: [ mysql ]
