---
- name: create pt-kill database
  mysql_db:
    name: "{{ mysql_ptkill_db }}"
    state: present

- name: init.d/pt-kill
  copy:
    src: pt-kill-init
    dest: /etc/init.d/pt-kill
    mode: 0755

- name: percona-toolkit config directory
  file:
    path: /etc/percona-toolkit
    state: directory

- name: pt-kill.conf
  template:
    src: pt-kill.conf.j2
    dest: /etc/percona-toolkit/pt-kill.conf
  notify: restart pt-kill
