---
# TODO service pt-kill restart cannot find /root/.my.cnf
# Soved: add export HOME=/root to /etc/init.d/pt-kill

- name: restart percona
  action: service name=mysql state=restarted

- name: stop percona
  action: service name=mysql state=stopped

- name: clear iblogfiles
  file: path={{ item }} state=absent
  with_fileglob:
    - "{{ mysql_datadir }}/ib_logfile*"

- name: start percona
  action: service name=mysql state=started

#- name: restart pt-kill
#  command: /etc/init.d/pt-kill restart

- name: restart pt-kill
  service: name=pt-kill state=restarted
