---
driver:
  name: docker
platforms:
  - name: ansible-role-mysql-1604
    image: solita/ubuntu-systemd:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
    destroy: ../resources/destroy.yml
  inventory:
    group_vars:
      all:
        mysql_innodb_log_file_size: 64M
  options:
    vvv: true